### ISSUE TITLE
Add maintenance jobs to run VACUUM FREEZE

### ISSUE THREAD

**Issue by pgnickb** [timescale/promscale_extension#416]
On systems with PG12 and in some cases, like compressing chunks it might make sense to run a manual VACUUM FREEZE instead of letting autovacuum handle the tables affected, as we have more knowledge about the access patterns than the generic tool which autovacuum is.
The fundamental limitation here is that a VACUUM command cannot be run in a transaction block (this includes functions), thus the maintenance jobs might not be suitable for this. We need to assess the possibility of such a solution and proceed accordingly.

**Comment by pgnickb** [comment]
Further investigation topics:
- Is it possible enhance compress-job to run vacuum freeze
- Is it possible to run vacuum within a transaction:
  * SPI call within a C procedure
  * directly call internal functions avoiding the checks (possibly has negative consequences)

Alternative:
Implement on the connector side.

Either way we want to stay clear of relying on the autovacuum.

**Comment by pgnickb** [comment]
> directly call internal functions avoiding the checks (possibly has negative consequences)
Consistently results in crashes within different code paths, no matter how much hackery I apply (I even tried to trick pg by swapping some of the sanity flags that are passed to the function on the go in gdb, to force pg to believe VACUUM is called from the top level context) 
This is a lost case, I'm convinced.

**Comment by jgpruitt** [comment]
- [ ] list chunks to be vacuumed
- [ ] vacuum freeze analyze a chunk
- [ ] concurrent workers to vacuum chunks
- [ ] periodically look for chunks and kick off workers if chunks found
- [ ] prevent more than one connector from running at a time
- [ ] prevent more than one iteration within a connector from running at a time
- [ ] wire in the configuration

**Comment by jgpruitt** [comment]
nice to haves

- [ ] new maintenance pool of database connections
- [ ] factor out the advisory lock stuff for vacuum and telemetry engines
