### ISSUE TITLE
Get the HA image published with the new version of timescaledb-tune

### ISSUE THREAD

**Issue by jgpruitt** [timescale/promscale_extension#490]

**Comment by jgpruitt** [comment]
- [ ] [released 0.14.0](https://github.com/timescale/timescaledb-tune/releases/tag/v0.14.0) of timescaledb-tune
- [ ] [PR](https://github.com/timescale/release-build-scripts/pull/58) to build and publish deb packages of timescaledb-tools which includes timescaledb-tune
- [ ] Rebuild/publish docker HA image

**Comment by jgpruitt** [comment]
Packages published:
https://github.com/timescale/release-build-scripts/actions/runs/2958448597

**Comment by jgpruitt** [comment]
A new release of the HA image is supposed to go out on Thursday anyway, so I’m going to leave that to the experts and piggy-back on that.
