### ISSUE TITLE
Maintenance Job Observability

### ISSUE THREAD

**Issue by sumerman** [timescale/promscale_extension#492]
This is a top-level tracking issue.

### Required metrics (some may exist already):
- [x] The amount of work that remains to be done
  - A size of a job queue if there is one
  - The number of chunks to be removed/compressed
  - Break down by the job type
- [ ] A histogram of job completion times
  - Break down by the job type
- [ ] A failure rate
  - Break down by the job type
  - Break down by the failure type
    - I don't want to over-specify it. The goal here is to be able to make common failure cases (if there are any) easily distinguishable.
- [x] The number of jobs running at any given moment
- [x] Last job activity and track inactivity time on a dashboard
- [x] Long-running statements 
  - Ideally, we should be able to limit them to only those, held by maintenance jobs
    - I expect `pg_stat_activity` to suffice for what I intend here. `pg_stat_statements` is shipped with the HA image, but not enabled by default. We can also make an optional metric based on `pg_stat_statements`.
 - [x] Locks by type if they don’t already.
   - Ideally, we should be able to limit them to only those, held by maintenance jobs

### Logs

We want to log into a (hyper)table, but transactional control may prevent us from extracting data from transactions that were rolled back. To circumvent that we can try:
 - To use an FDW pointed at the logging table
 - Come up with some other C/Rust-based trickery

## Tasks

- [x] Pick a single simple to-implement metric and add it all the way from the job description in SQL to a colorful panel in Grafana and a corresponding alert (if applicable)
  - [x] timescale/promscale#1597
  - [x] timescale/promscale#1598
  - [x] Survey (and mark as done) existing metrics while at it
- [ ] Implement support for collecting data from rolled-back transactions
  - [x] #495
  - [x] #496
  - [x] #497
- [x] Add every other metric in the list above

### Logging improvements (optional)

TBD after `Benchmark shmem vs FDW approaches.` is done. We can either leave logging as is or use one of the transaction-transcending data collection approaches to implement logging into a (hyper)table.

**Comment by JamesGuthrie** [comment]
One thing that I would find interesting to see would be something like per-metric stats on the last start time, last successful complete time, and last duration of the maintenance job processing of a specific metric (i.e. how much time was spent in `_prom_catalog.drop_metric_chunks` for a specific metric).

**Comment by sumerman** [comment]
Another idea: the amount of work VACUUM has to perform

**Comment by sumerman** [comment]
FTR https://github.com/timescale/promscale/issues/1232

**Comment by sumerman** [comment]
https://github.com/timescale/timescaledb/pull/4678 landed in the TimescaleDB
